### ISSUE TITLE
Monomial and Term

### ISSUE THREAD

**Issue by blegat** [blegat/CondensedMatterSOS.jl#1]
The variable is implemented in `examples/Draft.ipynb`. We should implement monomials and terms with something like
```julia
struct SpinMonomial <: MP.AbstractMonomial
    variables::Vector{SpinVariable}
end
struct SpinTerm{T} <: MP.AbstractTerm{T}
    coefficient::T
    monomial::SpinMonomial
end
```
The `variables` vector could for instance be `[σ^x_2, σ^y_8]`.
Note that if even if `N` different sites are used, the number of variables can be much smaller here so we cannot store all sites here an need to have some sparse storing as suggested. The issue with this is that multiplying this monomial by, say `σ^y_5` requires to insert it in the array.
Inserting an element in an array has linear time complexity which is not ideal, we would prefer logarithmic or constant time complexity.
With a hash table, we would have constant time complexity but the variables will not be sorted by site id which can be an issue for sorting monomials.
With a binary search tree, we would have logarithmic time complexity and the variables will be sorted, this seems like the best option here, and this might be available in DataStructures.jl

**Comment by Jacupo** [comment]
I used SortedDict from DataStructures.jl
