### ISSUE TITLE
Monomial comparison

### ISSUE THREAD

**Issue by blegat** [blegat/CondensedMatterSOS.jl#2]
The next step is to implement `Base.isless` between `SpinMonomial`'s.
For it to be efficient, we should iterate over the keys of each `SortedDict` in parallel, advancing for the one that has lower key.
A good example of this is:
https://github.com/JuliaAlgebra/MultivariatePolynomials.jl/blob/725642e2d159fc71ad34f119e932c0715973d017/src/comparison.jl#L55-L79
A good example of how to iterator over the keys of a `SortedDict` with more control is:
https://github.com/JuliaCollections/DataStructures.jl/blob/3814ac6bca6388f1848c057d6c981d4bf23813c2/src/sorted_dict.jl#L506-L528

**Comment by ecboghiu** [comment]
Hi, I have a question: how would `Base.isless` work in principle? Is `m1<m2` if the length of `m1` is less than that of `m2`? Is it an exponent comparison, i.e., `x*y^2*z > x ^y` because `[1,2,1]>[1,1,0]`? For Ising it wouldn't make much sense as we never have exponents greater than one. Thanks.

**Comment by blegat** [comment]
I would use grlex ordering to be consistent with DynamicPolynomials and TypedPolynomials. So we first compare the degrees. If they are equal, we compare degrees one by one until they are different

**Comment by Jacupo** [comment]
Ok thank you Benoit and Cristian, 
I pushed to the master the version with `isless` for variables and monomials in `operators.jl` and I added some tests.

**Comment by blegat** [comment]
Nice ! Quick question, why are these methods needed:
https://github.com/blegat/CondensedMatterSOS.jl/blob/52481bd52a075fbee0c1e719a6bfc98ca7e942da/src/operators.jl#L74-L79

**Comment by Jacupo** [comment]
Just in case one has a 0 degree monomial like in the case isless(sigmax*sigmax,sigmax). Then I do not know if we need some sort of ordering even for `SpintTerms`, or if we can move to the next step!

**Comment by blegat** [comment]
> if we need some sort of ordering even for SpintTerms

Ordering for terms is handled by MultivariatePolynomials.

**Comment by blegat** [comment]
Ok, this looks to be fixed @Jacupo note that you don't need to put any `;` at the end of your lines.
