### ISSUE TITLE
Polynomials

### ISSUE THREAD

**Issue by blegat** [blegat/CondensedMatterSOS.jl#4]
The type should be
```julia
struct SpinPolynomial{T} <: MP.AbstractPolynomial
    terms::Vector{SpintTerm{T}}
end
terms(p::SpinPolynomials) = p.terms
```
There might be a fallback in MultivariatePolynomials for everything once we define `terms` but I'm sure it's not the case, so the next step is to see which additional methods need to be implemented to make `+` work!

**Comment by Jacupo** [comment]
In the branch `Tentative-poly` I added a file called `Tentative-poly.jl` where I added few functions to make the `+` work.
Now `+` works with simple examples.

Some weird things happen  when I try to do `isless` with `SpinTerm` as arguments.
### Error 1
If I define 
```julia
monomialtype(::Type{<:Union{SpinVariable, SpinMonomial, SpinTerm, SpinPolynomial}}) = SpinMonomial
````
then I get the error
```
[1] termtype(::Type{CondensedMatterSOS.SpinVariable}) at /Users/jacoposurace/.julia/packages/MultivariatePolynomials/goWHi/src/term.jl:44
 [2] monomialtype(::Type{CondensedMatterSOS.SpinVariable}) at /Users/jacoposurace/.julia/packages/MultivariatePolynomials/goWHi/src/monomial.jl:13
 ... (the last 2 lines are repeated 39990 more times)
```
### Error 2
If I define
```julia
MP.monomialtype(::Type{<:Union{SpinVariable, SpinMonomial, SpinTerm, SpinPolynomial}}) = SpinMonomial
```
I get the error
```
ERROR: MethodError: no method matching isless(::CondensedMatterSOS.SpinPolynomial{Int64}, ::CondensedMatterSOS.SpinPolynomial{Int64}).
```
It looks like everything get upgraded to Polynomials.

### Strange Fix
If I instead use `Revise.jl` and after writing `using CondensedMatterSOS` I add 
```julia
MP.monomialtype(::Type{<:Union{SpinVariable, SpinMonomial, SpinTerm, SpinPolynomial}}) = SpinMonomial
```
then `isless` between terms works.
