### ISSUE TITLE
Ambiguous `promote_rule`

### ISSUE THREAD

**Issue by Jacupo** [blegat/CondensedMatterSOS.jl#9]
I cannot build the a vector like `[im*sz[1],-im*sz[1]]` because 
`typeof(im*sz[1])=CondensedMatterSOS.SpinTerm{Complex{Bool}}` while
`typeof(-im*sz[1])=CondensedMatterSOS.SpinTerm{Complex{Int64}}`.
The returner error while trying to build the vector is `MethodError: promote_rule(::Type{CondensedMatterSOS.SpinTerm{Complex{Bool}}}, ::Type{CondensedMatterSOS.SpinTerm{Complex{Int64}}}) is ambiguous.`
Why is the first type a `Complex{Bool}`?

**Comment by blegat** [comment]
Fixed by https://github.com/blegat/CondensedMatterSOS.jl/pull/11. The promotion ambiguity was fixed and it's no more a `Complex{Bool}` so it's double fixed :)
